name: "Test, Build & Deploy"
run-name: "${{ github.actor }} runs a pipeline."
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test"
    steps:
      -
        uses: actions/checkout@v3
      -
        name: "Checkout"
        uses: actions/checkout@v3
      -
        name: "Set up Docker BuildX"
        uses: docker/setup-buildx-action@v2
      -
        name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: "Build Image"
        uses: docker/build-push-action@v3
        with:
          file: "docker/testing.Dockerfile"
          push: true
          tags: ${{ vars.DOCKER_IMAGE_REPOSITORY }}/${{ vars.DOCKER_RUNNER_IMAGE }}:${{github.run_id}}, ${{ vars.DOCKER_IMAGE_REPOSITORY }}/${{ vars.DOCKER_RUNNER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ vars.DOCKER_IMAGE_REPOSITORY }}/${{ vars.DOCKER_RUNNER_IMAGE }}
          cache-to: type=inline
      -
        name: "Run"
        env:
          COVERAGE_THRESHOLD: ${{ vars.COVERAGE_THRESHOLD }}
          DOCKER_IMAGE_REPOSITORY: ${{ vars.DOCKER_IMAGE_REPOSITORY }}
          DOCKER_RUNNER_IMAGE: ${{ vars.DOCKER_RUNNER_IMAGE }}:${{github.run_id}}
        run: |
          docker run -e COVERAGE_THRESHOLD=$COVERAGE_THRESHOLD $DOCKER_IMAGE_REPOSITORY/$DOCKER_RUNNER_IMAGE
  build:
    needs: test
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      -
        uses: actions/checkout@v3
      -
        name: "Checkout"
        uses: actions/checkout@v3
      -
        name: "Set up Docker BuildX"
        uses: docker/setup-buildx-action@v2
      -
        name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: "Build"
        uses: docker/build-push-action@v3
        with:
          file: "docker/Dockerfile"
          push: true
          tags: ${{ vars.DOCKER_IMAGE_REPOSITORY }}/${{ vars.DOCKER_IMAGE }}:${{github.run_id}}, ${{ vars.DOCKER_IMAGE_REPOSITORY }}/${{ vars.DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ vars.DOCKER_IMAGE_REPOSITORY }}/${{ vars.DOCKER_IMAGE }}
          cache-to: type=inline


